config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root "pages#home"

  resources :brands  do 
    collection do 
      get 'search'
    end
    
    resources :products, except: [:index], controller: 'brands/products' do
      collection { post :import }
      collection { post :tech_sheet }
    end
    
    collection { post :import }

  end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :products, dependent: :destroy
	belongs_to :user

	mount_uploader :image, ImageUploader, mount_on: :image_file_name

	searchkick

	#has_attached_file :image,
	#:styles => {
  	#:tiny => "25x25#",
  	#:thumb => "100x100#",
  	#:small  => "150x150>",
  	#:medium => "300x300>" },
  	#:default_url => "default_:style.png"

	#has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/Wine-default.jpg"
	#validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	#def self.import(file)
		#CSV.foreach(file.path, headers: true) do |row|
		#	Brand.create! row.to_hash
		#end
	#end

	extend FriendlyId
	friendly_id :name, use: [:slugged, :history]
	#def should_generate_new_friendly_id?
    #	new_record?
  	#end

	def self.import(file, user_id)
	    CSV.foreach(file.path, headers: true) do |row|
	      Brand.create! row.to_hash.merge(user_id: user_id)
	    end
	end

	def self.to_csv 
		CSV.generate do |csv|
			csv << column_names
			all.each do |brand|
				csv << brand.attributes.values_at(*column_names)
			end
		end
	end

	def initial
	  return '?' if name.blank?
	  # name.[0].upcase (updated to get the first character )
	  name.slice(0).chr.upcase
	end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brand

  searchkick

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
  #def should_generate_new_friendly_id?
  #  new_record?
  #end
  
  #has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  #validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  mount_uploader :image, ImageUploader, mount_on: :image_file_name

  mount_uploader :shelf_talker, ShelfTalkerUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.

  mount_uploader :tech_sheet, TechSheetUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.

  mount_uploader :case_card, CaseCardUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.

  def self.import(file, user_id)
    CSV.foreach(file.path, headers: true) do |row|
      Product.create! row.to_hash.merge(user_id: user_id)
    end
  end

end

app/controllers/brands/products_controller.rb
class Brands::ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_user_admin, only: [:edit, :update, :destroy]

  # GET /products
  # GET /products.json

  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @brand = Brand.friendly.find(params[:brand_id])
    if request.path != product_path(@product)
      redirect_to @product, status: :moved_permanently
    end
    @products = Product.all
  end

  def show
    @brand = Brand.friendly.find(params[:brand_id])
    @product = @brand.products.friendly.find(params[:id])
  end

  # GET /products/new
  def new
    @brand = Brand.friendly.find(params[:brand_id])
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @brand = Brand.friendly.find(params[:brand_id])
    @product = Product.friendly.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @brand = Brand.friendly.find(params[:brand_id])
    @product = Product.new(product_params)
    @product.brand = @brand
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @brand, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @brand = Brand.friendly.find(params[:brand_id])
    @product = Product.friendly.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product was updated successfully."
      redirect_to @brand
    else
      flash[:error] = "There was an error updating the product."
      render :show
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @brand = Brand.friendly.find(params[:brand_id])
    @product = Product.friendly.find(params[:id])
    title = @product.name

    if @product.destroy 
      flash[:notice] = "#{title} was deleted successfully."
      redirect_to @brand
    else
      flash[:error] = "There was an error deleting the product."
      render :show
    end
  end

  def import
    if params[:file].present?
      @brand = Brand.friendly.find(params[:brand_id])
      Product.import(params[:file], current_user.id)
      redirect_to :back, notice: "Products added successfully"
    else
      redirect_to :back, notice: "You need to choose a file first!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :product_type, :product_subtype, :vintage, :country, :region, :brand_id, :user_id, :image, :remote_image_url, :appellation, :vineyard, :grape_varietals, :clones, :soil, :plot_characteristics, :yield, :vineyard_practices, :harvest, :yeast, :accolades, :producer, :bottle_size, :vinification_methods, :description, :shelf_talker, :tech_sheet, :case_card)
    end

    def require_user_admin
      if !current_user.admin?
        flash[:danger] = "Only admins can only edit brands and products"
        redirect_to brands_path
      end
    end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  # before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :require_user_admin, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search, :tech_sheet]
  #before_action :admin_user, only: [:edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def search
    if params[:search].present?
      @brands = Brand.search(params[:search])
    else
      @brands = Brand.all
    end
  end

  def index
    @brands = Brand.order('name ASC').paginate(:page => params[:page], :per_page => 30)
    @alpha = @brands.group_by{|u| u.name[0]}

    respond_to do |format|
      format.html
      format.csv { render text: @brands.to_csv }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.friendly.find(params[:id])
    if request.path != brand_path(@brand)
      redirect_to @brand, status: :moved_permanently
    end
    @products = @brand.products
  end

  # GET /brands/new
  def new
    @brand = current_user.brands.build
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = current_user.brands.build(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    if params[:file].present?
      Brand.import(params[:file], current_user.id)
      redirect_to brands_path, notice: "Brands added successfully"
    else
      redirect_to :back, notice: "You need to choose a file first!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :description, :viticulture, :image, :remote_image_url, :website, :country, :region, :appellation, :varietal, :soil_type, :enologist, :viticulturist, :vineyard_size, :total_production)
    end

    # looks up the brand through the user, and if the brand doesn't belong to that user, it won't exist, 
    # and it will redirect to the brands_path
    def correct_user
      @brand = current_user.brands.find_by(id: params[:id])
      redirect_to brands_path, notice: "Not authorized to edit this brand" if @brand.nil?
    end

    #def admin_user
    #  redirect_to brands_path unless current_user.admin?
    #end

    def require_user_admin
      if !current_user.admin?
        flash[:danger] = "Only admins can only edit brands and products"
        redirect_to brands_path
      end
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/products/_form.html.erb
<%= form_for [@brand, @product], html: { multipart: true } do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :product_type %><br>
    <%= f.text_field :product_type %>
  </div>
  <div class="field">
    <%= f.label :product_subtype %><br>
    <%= f.text_field :product_subtype %>
  </div>
  <div class="field">
    <%= f.label :vintage %><br>
    <%= f.text_field :vintage %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :appellation %><br>
    <%= f.text_field :appellation %>
  </div>
  <div class="field">
    <%= f.label :vineyard %><br>
    <%= f.text_field :vineyard %>
  </div>
  <div class="field">
    <%= f.label :grape_varietals %><br>
    <%= f.text_field :grape_varietals %>
  </div>
  <div class="field">
    <%= f.label :clones %><br>
    <%= f.text_field :clones %>
  </div>
  <div class="field">
    <%= f.label :soil %><br>
    <%= f.text_area :soil %>
  </div>
  <div class="field">
    <%= f.label :plot_characteristics %><br>
    <%= f.text_area :plot_characteristics %>
  </div>
  <div class="field">
    <%= f.label :yield %><br>
    <%= f.text_field :yield %>
  </div>
  <div class="field">
    <%= f.label :vineyard_practices %><br>
    <%= f.text_field :vineyard_practices %>
  </div>
  <div class="field">
    <%= f.label :harvest %><br>
    <%= f.text_field :harvest %>
  </div>
  <div class="field">
    <%= f.label :yeast %><br>
    <%= f.text_field :yeast %>
  </div>
  <div class="field">
    <%= f.label :accolades %><br>
    <%= f.text_area :accolades %>
  </div>
  <div class="field">
    <%= f.label :producer %><br>
    <%= f.text_field :producer %>
  </div>
  <div class="field">
    <%= f.label :bottle_size %><br>
    <%= f.text_field :bottle_size %>
  </div>
  <div class="field">
    <%= f.label :vinification_methods %><br>
    <%= f.text_area :vinification_methods %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :remote_image_url, "or image URL" %><br>
    <%= f.text_field :remote_image_url %>
  </div>
  <div class="field">
    <%= f.label :shelf_talker %><br>
    <%= f.file_field :shelf_talker %>
  </div>
  <div class="field">
    <%= f.label :tech_sheet %><br>
    <%= f.file_field :tech_sheet %>
  </div>
  <div class="field">
    <%= f.label :case_card %><br>
    <%= f.file_field :case_card %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/brands/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

app/views/brands/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Product type</th>
      <th>Product subtype</th>
      <th>Vintage</th>
      <th>Country</th>
      <th>Region</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.product_type %></td>
        <td><%= product.product_subtype %></td>
        <td><%= product.vintage %></td>
        <td><%= product.country %></td>
        <td><%= product.region %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= image_tag product.image.url(:thumb) %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/brands/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

app/views/brands/products/show.html.erb
<h2><%= @brand.name %></h2>
<div class="row">
  <div class="col-md-8">
    <% if !@brand.description.blank? %><p><strong>Description: </strong><%= simple_format(@brand.description) %></p><% end %>
    <% if !@brand.website.blank? %><p><strong><%= link_to "Website", @brand.website %></strong></p><% end %>
    <div class="row">
      <div class="col-md-6">
        <% if !@brand.viticulture.blank? %><p><strong>Viticulture:</strong> <%= @brand.viticulture %></p><% end %>
        <% if !@brand.country.blank? %><p><strong>Country:</strong> <%= @brand.country %></p><% end %>
        <% if !@brand.region.blank? %><p><strong>Region:</strong> <%= @brand.region %></p><% end %>
        <% if !@brand.appellation.blank? %><p><strong>Appellation:</strong> <%= @brand.appellation %></p><% end %>
        <% if !@brand.varietal.blank? %><p><strong>Varietal:</strong> <%= @brand.varietal %></p><% end %>
      </div>
      <div class="col-md-6">
        <% if !@brand.soil_type.blank? %><p><strong>Soil Type:</strong> <%= @brand.soil_type %></p><% end %>
        <% if !@brand.enologist.blank? %><p><strong>Enologist:</strong> <%= @brand.enologist %></p><% end %>
        <% if !@brand.viticulturist.blank? %><p><strong>Viticulturist:</strong> <%= @brand.viticulturist %></p><% end %>
        <% if !@brand.vineyard_size.blank? %><p><strong>Vineyard Size:</strong> <%= @brand.vineyard_size %></p><% end %>
        <% if !@brand.total_production.blank? %><p><strong>Total Production:</strong> <%= @brand.total_production %></p><% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <p><%= image_tag @brand.image_url(:medium).to_s %></p>
    <% if current_user && current_user.admin? %>
      <p><%= link_to 'Edit Brand', edit_brand_path(@brand) %> </p>
      <p><%= link_to 'Delete Brand', @brand, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %> 
  </div>
</div>

<hr />

<%= image_tag @product.image.url(:medium), class: 'pull-right' %>

<% if !@product.name.blank? %>
  <p>
    <strong>Name:</strong>
    <%= @product.name %>
  </p>
<% end %>

<% if !@product.product_type.blank? %>
  <p>
    <strong>Product type:</strong>
    <%= @product.product_type %>
  </p>
<% end %>

<% if !@product.product_subtype.blank? %>
  <p>
    <strong>Product subtype:</strong>
    <%= @product.product_subtype %>
  </p>
<% end %>

<% if !@product.vintage.blank? %>
  <p>
    <strong>Vintage:</strong>
    <%= @product.vintage %>
  </p>
<% end %>

<% if !@product.country.blank? %>
  <p>
    <strong>Country:</strong>
    <%= @product.country %>
  </p>
<% end %>

<% if !@product.region.blank? %>
  <p>
    <strong>Region:</strong>
    <%= @product.region %>
  </p>
<% end %>

<% if !@product.appellation.blank? %>
  <p>
    <strong>Appellation:</strong>
    <%= @product.appellation %>
  </p>
<% end %>

<% if !@product.vineyard.blank? %>
  <p>
    <strong>Vineyard:</strong>
    <%= @product.vineyard %>
  </p>
<% end %>

<% if !@product.grape_varietals.blank? %>
  <p>
    <strong>Grape Varietals - General:</strong>
    <%= @product.grape_varietals %>
  </p>
<% end %>

<% if !@product.clones.blank? %>
  <p>
    <strong>Grape Varietals - Clones:</strong>
    <%= @product.clones %>
  </p>
<% end %>

<% if !@product.soil.blank? %>
  <p>
    <strong>Soil:</strong>
    <%= @product.soil %>
  </p>
<% end %>

<% if !@product.plot_characteristics.blank? %>
  <p>
    <strong>Plot Characteristics:</strong>
    <%= @product.plot_characteristics %>
  </p>
<% end %>

<% if !@product.yield.blank? %>
  <p>
    <strong>Yield / Vine Density:</strong>
    <%= @product.yield %>
  </p>
<% end %>

<% if !@product.harvest.blank? %>
  <p>
    <strong>Harvest:</strong>
    <%= @product.harvest %>
  </p>
<% end %>

<% if !@product.yeast.blank? %>
  <p>
    <strong>Yeast:</strong>
    <%= @product.yeast %>
  </p>
<% end %>

<% if !@product.accolades.blank? %>
  <p>
    <strong>Accolades:</strong>
    <%= @product.accolades %>
  </p>
<% end %>

<% if !@product.producer.blank? %>
  <p>
    <strong>Producer:</strong>
    <%= @product.producer %>
  </p>
<% end %>

<% if !@product.bottle_size.blank? %>
  <p>
    <strong>Bottle Size:</strong>
    <%= @product.bottle_size %>
  </p>
<% end %>

<% if !@product.style.blank? %>
  <p>
    <strong>Style:</strong>
    <%= @product.style %>
  </p>
<% end %>

<% if !@product.vinification_methods.blank? %>
  <p>
    <strong>Vinification Methods:</strong>
    <%= simple_format(@product.vinification_methods) %>
  </p>
<% end %>

<% if !@product.description.blank? %>
  <p>
    <strong>Description / Tasting Notes:</strong>
    <%= simple_format(@product.description) %>
  </p>
<% end %>

<% if !@product.shelf_talker.blank? %>
  <p>
    <%= link_to "Shelf Talker", @product.shelf_talker_url, :target => '_blank' %>
  </p>
<% end %>

<% if !@product.tech_sheet.blank? %>
  <p>
    <%= link_to "Tech Sheet", @product.tech_sheet_url, :target => '_blank' %>
  </p>
<% end %>

<% if !@product.case_card.blank? %>
  <p>
    <%= link_to "Case Card", @product.case_card_url, :target => '_blank' %>
  </p>
<% end %>

<hr />

<p><%= link_to "Back to full product list", brand_path(@brand), class: 'btn btn-default btn-sm' %></p>
<p>
  <%= link_to "Edit", edit_brand_product_path(@brand, @product), class: 'btn btn-success btn-sm' %> 
  <%= link_to "Delete", [@brand, @product], method: :delete, confirm: "Are you sure you want to delete this product?", class: 'btn btn-danger btn-sm' %>
</p>