config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root "pages#home"

  resources :brands  do 
    collection do 
      get 'search'
    end
    
    resources :products, except: [:index], controller: 'brands/products' do
      collection { post :import }
      collection { post :tech_sheet }
    end
    
    collection { post :import }

  end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :products, dependent: :destroy
	belongs_to :user

	mount_uploader :image, ImageUploader, mount_on: :image_file_name

	searchkick

	#has_attached_file :image,
	#:styles => {
  	#:tiny => "25x25#",
  	#:thumb => "100x100#",
  	#:small  => "150x150>",
  	#:medium => "300x300>" },
  	#:default_url => "default_:style.png"

	#has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/Wine-default.jpg"
	#validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	#def self.import(file)
		#CSV.foreach(file.path, headers: true) do |row|
		#	Brand.create! row.to_hash
		#end
	#end

	extend FriendlyId
	friendly_id :name, use: [:slugged, :history]
	#def should_generate_new_friendly_id?
    #	new_record?
  	#end

	def self.import(file, user_id)
	    CSV.foreach(file.path, headers: true) do |row|
	      Brand.create! row.to_hash.merge(user_id: user_id)
	    end
	end

	def self.to_csv 
		CSV.generate do |csv|
			csv << column_names
			all.each do |brand|
				csv << brand.attributes.values_at(*column_names)
			end
		end
	end

	def initial
	  return '?' if name.blank?
	  # name.[0].upcase (updated to get the first character )
	  name.slice(0).chr.upcase
	end

end

app/controllers/brands/products_controller.rb
class Brands::ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_user_admin, only: [:edit, :update, :destroy]

  # GET /products
  # GET /products.json

  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @brand = Brand.friendly.find(params[:brand_id])
    if request.path != product_path(@product)
      redirect_to @product, status: :moved_permanently
    end
    @products = Product.all
  end

  def show
    @brand = Brand.friendly.find(params[:brand_id])
    @product = @brand.products.friendly.find(params[:id])
  end

  # GET /products/new
  def new
    @brand = Brand.friendly.find(params[:brand_id])
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @brand = Brand.friendly.find(params[:brand_id])
    @product = Product.friendly.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @brand = Brand.friendly.find(params[:brand_id])
    @product = Product.new(product_params)
    @product.brand = @brand
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @brand, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @brand = Brand.friendly.find(params[:brand_id])
    @product = Product.friendly.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product was updated successfully."
      redirect_to @brand
    else
      flash[:error] = "There was an error updating the product."
      render :show
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @brand = Brand.friendly.find(params[:brand_id])
    @product = Product.friendly.find(params[:id])
    title = @product.name

    if @product.destroy 
      flash[:notice] = "#{title} was deleted successfully."
      redirect_to @brand
    else
      flash[:error] = "There was an error deleting the product."
      render :show
    end
  end

  def import
    if params[:file].present?
      @brand = Brand.friendly.find(params[:brand_id])
      Product.import(params[:file], current_user.id)
      redirect_to :back, notice: "Products added successfully"
    else
      redirect_to :back, notice: "You need to choose a file first!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :product_type, :product_subtype, :vintage, :country, :region, :brand_id, :user_id, :image, :remote_image_url, :appellation, :vineyard, :grape_varietals, :clones, :soil, :plot_characteristics, :yield, :vineyard_practices, :harvest, :yeast, :accolades, :producer, :bottle_size, :vinification_methods, :description, :shelf_talker, :tech_sheet, :case_card)
    end

    def require_user_admin
      if !current_user.admin?
        flash[:danger] = "Only admins can only edit brands and products"
        redirect_to brands_path
      end
    end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  # before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :require_user_admin, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search, :tech_sheet]
  #before_action :admin_user, only: [:edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def search
    if params[:search].present?
      @brands = Brand.search(params[:search])
    else
      @brands = Brand.all
    end
  end

  def index
    @brands = Brand.order('name ASC').paginate(:page => params[:page], :per_page => 30)
    @alpha = @brands.group_by{|u| u.name[0]}

    respond_to do |format|
      format.html
      format.csv { render text: @brands.to_csv }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.friendly.find(params[:id])
    if request.path != brand_path(@brand)
      redirect_to @brand, status: :moved_permanently
    end
    @products = @brand.products
  end

  # GET /brands/new
  def new
    @brand = current_user.brands.build
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = current_user.brands.build(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    if params[:file].present?
      Brand.import(params[:file], current_user.id)
      redirect_to brands_path, notice: "Brands added successfully"
    else
      redirect_to :back, notice: "You need to choose a file first!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :description, :viticulture, :image, :remote_image_url, :website, :country, :region, :appellation, :varietal, :soil_type, :enologist, :viticulturist, :vineyard_size, :total_production)
    end

    # looks up the brand through the user, and if the brand doesn't belong to that user, it won't exist, 
    # and it will redirect to the brands_path
    def correct_user
      @brand = current_user.brands.find_by(id: params[:id])
      redirect_to brands_path, notice: "Not authorized to edit this brand" if @brand.nil?
    end

    #def admin_user
    #  redirect_to brands_path unless current_user.admin?
    #end

    def require_user_admin
      if !current_user.admin?
        flash[:danger] = "Only admins can only edit brands and products"
        redirect_to brands_path
      end
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_for @brand, html: { multipart: true } do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :viticulture %><br>
    <%= f.text_field :viticulture %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :appellation %><br>
    <%= f.text_field :appellation %>
  </div>
  <div class="field">
    <%= f.label :varietal %><br>
    <%= f.text_field :varietal %>
  </div>
  <div class="field">
    <%= f.label :soil_type %><br>
    <%= f.text_field :soil_type %>
  </div>
  <div class="field">
    <%= f.label :viticulturist %><br>
    <%= f.text_field :viticulturist %>
  </div>
  <div class="field">
    <%= f.label :enologist %><br>
    <%= f.text_field :enologist %>
  </div>
  <div class="field">
    <%= f.label :vineyard_size %><br>
    <%= f.text_field :vineyard_size %>
  </div>
  <div class="field">
    <%= f.label :total_production %><br>
    <%= f.text_field :total_production %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<h1>Brands</h1>

<div class="row">
  <% if @brands.exists? %>
    <% @brands.each_slice(4) do |brand| %>
      <div class="row">
        <% brand.each do |brand| %>
          <div class="col-md-3">
            <div class="center">
              <%= link_to (image_tag brand.image_url(:small).to_s, class: 'img-thumbnail'), brand %>
              <p><%= brand.name %> <br />
              <em><%= brand.appellation %></em></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

<div class="row well">
  <% if current_user && current_user.admin? %>
  <div class="col-md-4">
    <h3>Add a New Brand</h3>
    <%= link_to "Add New", new_brand_path, class: 'btn btn-success btn-sm' %> 
  </div>
  <div class="col-md-4">
    <h3>Import Brands</h3>
      <%= form_tag import_brands_path, multipart: true do %>
        <p>
        <%= file_field_tag :file %>
        </p>
        <%= submit_tag "Upload Brands", class: 'btn btn-info btn-sm' %>
      <% end %>
  </div>
  <div class="col-md-4">
    <h3>Download Brands</h3>
    <%= link_to "Report", brands_path(format: "csv"), class: 'btn btn-primary btn-sm' %>  
  </div>
  <% end %>
</div>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/search.html.erb
<div class="row">
	<h3>Search Results: </h3>
  		<% @brands.each do |brand| %>
       		<p><%= link_to(brand.name, brand) %><br /></p>
  		<% end %>
</div>

app/views/brands/show.html.erb
<h2><%= @brand.name %></h2>

<div class="row">
  <div class="col-md-8">
    <% if !@brand.description.blank? %><p><%= simple_format(@brand.description) %></p><% end %>
    <% if !@brand.website.blank? %><p><strong><%= link_to "Website", @brand.website %></strong></p><% end %>
    <div class="row">
      <div class="col-md-6">
        <% if !@brand.viticulture.blank? %><p><strong>Viticulture:</strong> <%= @brand.viticulture %></p><% end %>
        <% if !@brand.country.blank? %><p><strong>Country:</strong> <%= @brand.country %></p><% end %>
        <% if !@brand.region.blank? %><p><strong>Region:</strong> <%= @brand.region %></p><% end %>
        <% if !@brand.appellation.blank? %><p><strong>Appellation:</strong> <%= @brand.appellation %></p><% end %>
        <% if !@brand.varietal.blank? %><p><strong>Varietal:</strong> <%= @brand.varietal %></p><% end %>
      </div>
      <div class="col-md-6">
        <% if !@brand.soil_type.blank? %><p><strong>Soil Type:</strong> <%= @brand.soil_type %></p><% end %>
        <% if !@brand.enologist.blank? %><p><strong>Enologist:</strong> <%= @brand.enologist %></p><% end %>
        <% if !@brand.viticulturist.blank? %><p><strong>Viticulturist:</strong> <%= @brand.viticulturist %></p><% end %>
        <% if !@brand.vineyard_size.blank? %><p><strong>Vineyard Size:</strong> <%= @brand.vineyard_size %></p><% end %>
        <% if !@brand.total_production.blank? %><p><strong>Total Production:</strong> <%= @brand.total_production %></p><% end %>
      </div>
    </div>
  </div>
	<div class="col-md-4">
		<p><%= image_tag @brand.image_url(:medium).to_s %></p>
		<% if current_user && current_user.admin? %>
			<p><%= link_to 'Edit Brand', edit_brand_path(@brand) %> </p>
			<p><%= link_to 'Delete Brand', @brand, method: :delete, data: { confirm: 'Are you sure?' } %></p>
		<% end %>	
	</div>
</div>

<hr>

<h3>Products</h3>

<div class="media">
	<div class="media-body">
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th>Link</th>
					<th>Type</th>
					<th>Subtype</th>
					<th>Vintage</th>
					<th>Country</th>
					<th>Region</th>
					<th>Image</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</thead>
			<tbody>
				<% @products.each do |product| %>
				<tr>
					<td><%= product.name %></td>
					<td><%= link_to "Show Tech Sheet", brand_product_path(@brand, product) %><br />
					</td>
					<td><%= product.product_type %></td>
					<td><%= product.product_subtype %></td>
					<td><%= product.vintage %></td>
					<td><%= product.country %></td>
					<td><%= product.region %></td>
					<td><%= image_tag product.image_url(:thumb).to_s %></td>
					<% if current_user && current_user.admin? %>
						<td><%= link_to "Delete", [@brand, product], method: :delete, confirm: "Are you sure you want to delete this product?" %></td>
						<td><%= link_to "Edit", edit_brand_product_path(@brand, product) %></td>

					<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<%= link_to 'Back', brands_path, class: 'btn btn-default btn-sm' %>

<% if current_user && current_user.admin? %>

	<%= link_to 'Add new product', new_brand_product_path(@brand), class: 'btn btn-success btn-sm pull-right' %>

	<h3>Import Products</h3>
	  <%= form_tag import_brand_products_path(@brand, @product), multipart: true do %>
	    <p>
	    <%= file_field_tag :file %>
	    </p>
	    <%= submit_tag "Upload Products", class: 'btn btn-info btn-sm' %>
	  <% end %>

<% end %>

app/views/brands/tech_sheet.html.erb
<p>
  <strong>Brand Name:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>Product Name:</strong>
  <%= @product.name %>
</p>