config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root "pages#home"

  resources :brands  do 
    collection do 
      get 'search'
    end
    
    resources :products, except: [:index], controller: 'brands/products' do
      collection { post :import }
      collection { post :tech_sheet }
    end
    
    collection { post :import }

  end

end

app/views/layouts/_footer.html.erb
<footer>
	<div class="container center">
		<p><small>Copyright &copy; 2015 Regal Wine Imports, All Rights Reserved </small></p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to image_tag('Regal-Logo-thumb.png'), root_path, class: 'style_image' %>

  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Brands", brands_path %></li>

      <% if current_user %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %> 
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>  
      <%= form_tag search_brands_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Regalwine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	
	
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>

      <%= yield %>
    </div>

  <%= render 'layouts/footer' %>

</body>
</html>